### ISSUE TITLE
Causes application freeze when cancelling a GCancellable in the main thread

### ISSUE THREAD

**Issue by mcrha** [PackageKit/PackageKit#565]
Moving this from a downstream bug report:
https://gitlab.gnome.org/GNOME/gnome-software/-/issues/1827

The below backtrace shows an application being stuck in the main thread on a D-Bus call made by the PackageKit from `pk_client_cancellable_cancel_cb () at ../lib/packagekit-glib2/pk-client.c:95`, as a reaction to the `g_cancellable_cancel()` call. It shows doing D-Bus blocking calls in the main thread is not ideal.

I'd say calling the `g_cancellable_cancel()` in the main thread is pretty common thing, it might be the most often way to cancel any pending actions by the users.

Backtrace:
```
(gdb) bt full
#0  syscall () at ../sysdeps/unix/sysv/linux/x86_64/syscall.S:38
#1  0x00007f9d6383142c in g_mutex_lock_slowpath (mutex=mutex@entry=0x55b915969668) at ../glib/gthread-posix.c:1493
#2  0x00007f9d63831473 in g_mutex_lock (mutex=mutex@entry=0x55b915969668) at ../glib/gthread-posix.c:1517
#3  0x00007f9d63a2c024 in g_dbus_connection_send_message_with_reply
    (connection=0x55b915969650, message=0x55b917d54f20, flags=G_DBUS_SEND_MESSAGE_FLAGS_NONE, timeout_msec=2147483647, out_serial=0x7ffefef7c544, cancellable=0x0, callback=0x7f9d63a39a20 <g_dbus_connection_call_done>, user_data=0x55b916429340) at ../gio/gdbusconnection.c:2017
        __func__ = "g_dbus_connection_send_message_with_reply"
#4  0x00007f9d63a37806 in g_dbus_connection_call_internal
    (connection=0x55b915969650, bus_name=0x55b918aaba10 ":1.39", object_path=0x55b917ef45c0 "/10227_deddddba", interface_name=0x55b9170cecb0 "org.freedesktop.PackageKit.Transaction", method_name=0x7f9d62b3b3a2 "Cancel", parameters=<optimized out>, reply_type=0x7f9d63a9771c, flags=G_DBUS_CALL_FLAGS_NONE, timeout_msec=2147483647, fd_list=0x0, cancellable=0x0, callback=0x7f9d63a42280 <reply_cb>, user_data=0x55b916a24a80)
    at ../gio/gdbusconnection.c:5953
        state = 0x7f9d24fcd400
        task = 0x55b916429340
        message = 0x55b917d54f20
        serial = 0
        __func__ = "g_dbus_connection_call_internal"
#5  0x00007f9d63a4259d in g_dbus_proxy_call_internal
    (proxy=0x7f9d20a9e480, method_name=method_name@entry=0x7f9d62b3b3a2 "Cancel", parameters=parameters@entry=0x0, flags=flags@entry=G_DBUS_CALL_FLAGS_NONE, timeout_msec=timeout_msec@entry=2147483647, fd_list=fd_list@entry=0x0, cancellable=0x0, callback=0x7f9d62b0d040 <pk_client_cancel_cb>, user_data=0x7f9d3d0205b0) at ../gio/gdbusproxy.c:2719
        task = 0x55b916a24a80
        was_split = <optimized out>
        split_interface_name = 0x0
        split_method_name = 0x0
        target_method_name = 0x7f9d62b3b3a2 "Cancel"
        target_interface_name = 0x55b9170cecb0 "org.freedesktop.PackageKit.Transaction"
        destination = 0x55b918aaba10 ":1.39"
        reply_type = 0x0
        my_callback = 0x7f9d63a42280 <reply_cb>
        __func__ = "g_dbus_proxy_call_internal"
#6  0x00007f9d63a4274a in g_dbus_proxy_call
    (proxy=<optimized out>, method_name=method_name@entry=0x7f9d62b3b3a2 "Cancel", parameters=parameters@entry=0x0, flags=flags@entry=G_DBUS_CALL_FLAGS_NONE, timeout_msec=timeout_msec@entry=2147483647, cancellable=cancellable@entry=0x0, callback=0x7f9d62b0d040 <pk_client_cancel_cb>, user_data=0x7f9d3d0205b0) at ../gio/gdbusproxy.c:2960
#7  0x00007f9d62b0a3e3 in pk_client_cancellable_cancel_cb (cancellable=<optimized out>, user_data=<optimized out>) at ../lib/packagekit-glib2/pk-client.c:95
        weak_ref = <optimized out>
        state = 0x55b91628ad40
#8  0x00007f9d638dbdb0 in g_closure_invoke (closure=0x55b916ff96c0, return_value=0x0, n_param_values=1, param_values=0x7ffefef7c860, invocation_hint=0x7ffefef7c7e0) at ../gobject/gclosure.c:830
        marshal = 0x7f9d638de0d0 <g_cclosure_marshal_VOID__VOID>
        marshal_data = 0x0
        in_marshal = 0
        real_closure = 0x55b916ff96a0
        __func__ = "g_closure_invoke"
#9  0x00007f9d639084d6 in signal_emit_unlocked_R.isra.0
    (node=node@entry=0x55b91596ce80, detail=detail@entry=0, instance=instance@entry=0x55b915f5c620, emission_return=emission_return@entry=0x0, instance_and_params=instance_and_params@entry=0x7ffefef7c860)
    at ../gobject/gsignal.c:3743
        tmp = <optimized out>
        handler = 0x55b9169b6a40
        accumulator = 0x0

                  emission = {next = 0x7ffefef7cc30, instance = 0x55b915f5c620, ihint = {signal_id = 26, detail = 0, run_type = (G_SIGNAL_RUN_FIRST | G_SIGNAL_ACCUMULATOR_FIRST_RUN)}, state = EMISSION_RUN, chain_type = 0x4}
        hlist = <optimized out>
        handler_list = 0x55b918319b40
        return_accu = 0x0

                      accu = {g_type = 0x0, data = {{v_int = 0, v_uint = 0, v_long = 0, v_ulong = 0, v_int64 = 0, v_uint64 = 0, v_float = 0, v_double = 0, v_pointer = 0x0}, {v_int = 0, v_uint = 0, v_long = 0, v_ulong = 0, v_int64 = 0, v_uint64 = 0, v_float = 0, v_double = 0, v_pointer = 0x0}}}
        signal_id = 26
        max_sequential_handler_number = 1880334
        return_value_altered = <optimized out>
#10 0x00007f9d638f8a2e in g_signal_emit_valist (instance=<optimized out>, signal_id=<optimized out>, detail=<optimized out>, var_args=var_args@entry=0x7ffefef7ca10) at ../gobject/gsignal.c:3496
        instance_and_params = 0x7ffefef7c860
        signal_return_type = <optimized out>
        param_values = 0x7ffefef7c878
        node = <optimized out>
        i = <optimized out>
        n_params = <optimized out>
        __func__ = "g_signal_emit_valist"
#11 0x00007f9d638f8cb3 in g_signal_emit (instance=instance@entry=0x55b915f5c620, signal_id=<optimized out>, detail=detail@entry=0) at ../gobject/gsignal.c:3553
        var_args = {{gp_offset = 24, fp_offset = 48, overflow_arg_area = 0x7ffefef7caf0, reg_save_area = 0x7ffefef7ca30}}
#12 0x00007f9d63974857 in g_cancellable_cancel (cancellable=0x55b915f5c620) at ../gio/gcancellable.c:513
        priv = 0x55b915f5c600
#13 g_cancellable_cancel (cancellable=0x55b915f5c620) at ../gio/gcancellable.c:487
#14 0x000055b914b7def9 in gs_update_monitor_network_changed_cb (network_monitor=<optimized out>, available=<optimized out>, monitor=0x7f9d3c09c890) at ../src/gs-update-monitor.c:1307
#15 gs_update_monitor_network_changed_cb (network_monitor=0x55b915a272c0, available=<optimized out>, monitor=0x7f9d3c09c890) at ../src/gs-update-monitor.c:1300
#16 0x00007f9d638dbdb0 in g_closure_invoke (closure=0x55b9161b6d30, return_value=0x0, n_param_values=2, param_values=0x7ffefef7ccc0, invocation_hint=0x7ffefef7cc40) at ../gobject/gclosure.c:830
        marshal = 0x7f9d638de160 <g_cclosure_marshal_VOID__BOOLEAN>
        marshal_data = 0x0
        in_marshal = 0
        real_closure = 0x55b9161b6d10
        __func__ = "g_closure_invoke"
#17 0x00007f9d639084d6 in signal_emit_unlocked_R.isra.0
    (node=node@entry=0x55b915a12aa0, detail=detail@entry=0, instance=instance@entry=0x55b915a272c0, emission_return=emission_return@entry=0x0, instance_and_params=instance_and_params@entry=0x7ffefef7ccc0)
    at ../gobject/gsignal.c:3743
        tmp = <optimized out>
        handler = 0x55b915fade00
        accumulator = 0x0
        emission = {next = 0x0, instance = 0x55b915a272c0, ihint = {signal_id = 86, detail = 0, run_type = (G_SIGNAL_RUN_FIRST | G_SIGNAL_ACCUMULATOR_FIRST_RUN)}, state = EMISSION_RUN, chain_type = 0x4}
        hlist = <optimized out>
        handler_list = 0x55b915a33f00
        return_accu = 0x0

                      accu = {g_type = 0x0, data = {{v_int = 0, v_uint = 0, v_long = 0, v_ulong = 0, v_int64 = 0, v_uint64 = 0, v_float = 0, v_double = 0, v_pointer = 0x0}, {v_int = 0, v_uint = 0, v_long = 0, v_ulong = 0, v_int64 = 0, v_uint64 = 0, v_float = 0, v_double = 0, v_pointer = 0x0}}}
        signal_id = 86
        max_sequential_handler_number = 1880332
        return_value_altered = <optimized out>
#18 0x00007f9d638f8a2e in g_signal_emit_valist (instance=<optimized out>, signal_id=<optimized out>, detail=<optimized out>, var_args=var_args@entry=0x7ffefef7ce90) at ../gobject/gsignal.c:3496
        instance_and_params = 0x7ffefef7ccc0
        signal_return_type = <optimized out>
        param_values = 0x7ffefef7ccd8
        node = <optimized out>
        i = <optimized out>
        n_params = <optimized out>
        __func__ = "g_signal_emit_valist"
#19 0x00007f9d638f8cb3 in g_signal_emit (instance=instance@entry=0x55b915a272c0, signal_id=<optimized out>, detail=detail@entry=0) at ../gobject/gsignal.c:3553
        var_args = {{gp_offset = 32, fp_offset = 48, overflow_arg_area = 0x7ffefef7cf70, reg_save_area = 0x7ffefef7ceb0}}
#20 0x00007f9d639ab6ef in emit_network_changed (user_data=0x55b915a272c0) at ../gio/gnetworkmonitorbase.c:445
        is_available = 1
        monitor = 0x55b915a272c0
#21 emit_network_changed (user_data=user_data@entry=0x55b915a272c0) at ../gio/gnetworkmonitorbase.c:427
        monitor = 0x55b915a272c0
#22 0x00007f9d637dd4cb in g_idle_dispatch (source=0x55b9168d2600, callback=0x7f9d639ab670 <emit_network_changed>, user_data=0x55b915a272c0) at ../glib/gmain.c:5935
        again = <optimized out>
#23 0x00007f9d637e0faf in g_main_dispatch (context=0x55b91593e000) at ../glib/gmain.c:3417
        dispatch = 0x7f9d637dd4b0 <g_idle_dispatch>
        prev_source = 0x0
        begin_time_nsec = 68942941968053
        was_in_call = 0
        user_data = 0x55b915a272c0
        callback = 0x7f9d639ab670 <emit_network_changed>
        cb_funcs = 0x7f9d638c63e0 <g_source_callback_funcs>
        cb_data = 0x7f9d48024220
        need_destroy = <optimized out>
        source = 0x55b9168d2600
        current = 0x55b91596cf30
        i = 0
#24 g_main_context_dispatch (context=0x55b91593e000) at ../glib/gmain.c:4135
#25 0x00007f9d638362c8 in g_main_context_iterate.constprop.0 (context=context@entry=0x55b91593e000, block=block@entry=1, dispatch=dispatch@entry=1, self=<optimized out>) at ../glib/gmain.c:4211
        max_priority = 100
        timeout = 0
        some_ready = 1
        nfds = 4
        allocated_nfds = <optimized out>
        fds = <optimized out>
        begin_time_nsec = 68942941961050
#26 0x00007f9d637de940 in g_main_context_iteration (context=context@entry=0x55b91593e000, may_block=may_block@entry=1) at ../glib/gmain.c:4276
        retval = <optimized out>
#27 0x00007f9d63a05aed in g_application_run (application=0x55b915913100, argc=argc@entry=2, argv=argv@entry=0x7ffefef7d298) at ../gio/gapplication.c:2569
        arguments = 0x55b915971290
        status = 0
        context = 0x55b91593e000
        acquired_context = <optimized out>
        __func__ = "g_application_run"
#28 0x000055b914b2e486 in main (argc=2, argv=0x7ffefef7d298) at ../src/gs-main.c:49
        status = 0
        appinfo = 0x55b915944850
        application = 0x55b915913100
        debug = 0x55b915905600
```

**Comment by dimaryaz** [comment]
This happened to me again; attaching the backtrace of all threads now.

[gnome-software.txt](https://github.com/PackageKit/PackageKit/files/9355112/gnome-software.txt)
