### ISSUE TITLE
g_object_unref: assertion 'G_IS_OBJECT (object)' failed` (during pkcon interactive install )

### ISSUE THREAD

**Issue by sidt4** [PackageKit/PackageKit#731]
The following message is displayed when we do interactive `install` / `remove` via `pkcon` and decline with a `N` response.

`(pkcon:90750): GLib-GObject-CRITICAL **: 12:48:45.944: g_object_unref: assertion 'G_IS_OBJECT (object)' failed`

Though the stack trace appears different, I guess it's related to https://github.com/PackageKit/PackageKit/issues/730, since this issue is not seen when the `GTask` refcount issue is fixed.

### Backtrace:

```
gdb) bt
#0  g_logv (log_domain=0x7f29a6f9fef3 "GLib-GObject", log_level=G_LOG_LEVEL_CRITICAL, format=<optimized out>, args=args@entry=0x7ffedd21e540) at ../../../glib/gmessages.c:1423
#1  0x00007f29a701ef03 in g_log (log_domain=<optimized out>, log_level=<optimized out>, format=<optimized out>) at ../../../glib/gmessages.c:1461
#2  0x00007f29a70125fd in g_source_callback_unref (cb_data=0x559fa9be2e60) at ../../../glib/gmain.c:1758
#3  g_source_callback_unref (cb_data=0x559fa9be2e60) at ../../../glib/gmain.c:1751
#4  0x00007f29a7012f2f in g_source_destroy_internal (source=source@entry=0x559fa9be2d80, context=context@entry=0x559fa9bcbd40, have_lock=have_lock@entry=1) at ../../../glib/gmain.c:1423
#5  0x00007f29a701313c in g_main_dispatch (context=context@entry=0x559fa9bcbd40) at ../../../glib/gmain.c:3506
#6  0x00007f29a7016317 in g_main_context_dispatch_unlocked (context=0x559fa9bcbd40) at ../../../glib/gmain.c:4284
#7  g_main_context_iterate_unlocked (context=0x559fa9bcbd40, block=block@entry=1, dispatch=dispatch@entry=1, self=<optimized out>) at ../../../glib/gmain.c:4349
#8  0x00007f29a7016c1f in g_main_loop_run (loop=0x559fa9bcbf50) at ../../../glib/gmain.c:4551
#9  0x0000559fa872887f in main (argc=3, argv=0x7ffedd21ebc8) at ../client/pk-console.c:2400
```

**Comment by ximion** [comment]
Let's close it, we can always reopen the issue or create a new one. Thanks for doing some issue-maintenance! :-)
