### ISSUE TITLE
pk_task_generic_finish: assertion 'G_IS_SIMPLE_ASYNC_RESULT (res)' failed

### ISSUE THREAD

**Issue by mikwee** [PackageKit/PackageKit#747]
Ran `pkcon get-transactions` on Fedora 40, and got this error:
```
Getting transactions                    [=========================]         
Finished                                [=========================]         

(pkcon:11343): PackageKit-CRITICAL **: 11:56:10.603: pk_task_generic_finish: assertion 'G_IS_SIMPLE_ASYNC_RESULT (res)' failed
Segmentation fault (core dumped)
```
My vague knowledge of segfault makes me think it's a RAM issue, but I was told to open an issue here, so I did.

**Comment by sidt4** [comment]
> My vague knowledge of segfault makes me think it's a RAM issue

Not a RAM issue.

### On Debian with `packagekit-1.2.8`.

```
$ pkcon get-transactions
Getting transactions                    [=========================]         
Finished                                [=========================]         

(pkcon:142994): PackageKit-CRITICAL **: 10:55:57.869: pk_task_generic_finish: assertion 'G_IS_SIMPLE_ASYNC_RESULT (res)' failed
Segmentation fault (core dumped)
```

### On latest git `packagekit` (with port to `GTask`):

```
$ pkcon get-transactions
Getting transactions                    [=========================]         
Finished                                [=========================]         
Segmentation fault (core dumped)
```

### Backtrace:

```
(gdb) bt
#0  0x00007f03fc79cd8c in pk_task_generic_finish (task=0x5555862162c0 [PkTaskText], res=0x555586213350, error=0x7fff186777a8) at ../lib/packagekit-glib2/pk-task.c:2192
#1  0x0000555585a2d6b6 in pk_console_finished_cb (object=0x5555862162c0 [PkTaskText], res=0x555586213350, data=0x555586203cb0) at ../client/pk-console.c:663
#2  0x00007f03fc4666b3 in g_task_return_now (task=task@entry=0x555586213350 [GTask]) at ../../../gio/gtask.c:1361
#3  0x00007f03fc467353 in g_task_return (type=<optimized out>, task=0x555586213350 [GTask]) at ../../../gio/gtask.c:1430
#4  g_task_return (task=0x555586213350 [GTask], type=<optimized out>) at ../../../gio/gtask.c:1387
#5  0x00007f03fc767435 in pk_client_state_finish (state=0x555586213210 [PkClientState], error=0x0) at ../lib/packagekit-glib2/pk-client.c:245
#6  0x00007f03fc769b33 in pk_client_signal_finished (state=0x555586213210 [PkClientState], exit_enum=PK_EXIT_ENUM_SUCCESS, runtime=0) at ../lib/packagekit-glib2/pk-client.c:1202
#7  0x00007f03fc769eac in pk_client_signal_cb
    (proxy=0x555586210d90 [GDBusProxy], sender_name=0x5555862137f0 ":1.1379", signal_name=0x55558621d440 "Finished", parameters=0x7f03dc0038c0, user_data=0x55558621b920)
...
```
